export const mockProducts = [
  {
    id: 1,
    name: 'iPhone 15 Pro 128GB',
    slug: 'iphone-15-pro-128gb',
    brand: 'Apple',
    category: 'Smartphones',
    categorySlug: 'smartphones',
    images: ['https://via.placeholder.com/300x300/0ea5e9/ffffff?text=iPhone+15+Pro'],
    minPrice: 12999,
    maxPrice: 14500,
    offersCount: 3,
    specifications: { 'Écran': '6.1 pouces', 'RAM': '8 GB' },
    createdAt: new Date().toISOString(),
  },
  {
    id: 2,
    name: 'Samsung Galaxy S24 Ultra 256GB',
    slug: 'samsung-galaxy-s24-ultra',
    brand: 'Samsung',
    category: 'Smartphones',
    categorySlug: 'smartphones',
    images: ['https://via.placeholder.com/300x300/6366f1/ffffff?text=Galaxy+S24'],
    minPrice: 15299,
    maxPrice: 16999,
    offersCount: 4,
    specifications: { 'Écran': '6.8 pouces', 'RAM': '12 GB' },
    createdAt: new Date().toISOString(),
  },
  {
    id: 3,
    name: 'MacBook Air M3 13"',
    slug: 'macbook-air-m3',
    brand: 'Apple',
    category: 'Ordinateurs',
    categorySlug: 'ordinateurs',
    images: ['https://via.placeholder.com/300x300/10b981/ffffff?text=MacBook+Air'],
    minPrice: 17499,
    maxPrice: 18999,
    offersCount: 2,
    specifications: { 'Écran': '13.6 pouces', 'Processeur': 'M3' },
    createdAt: new Date().toISOString(),
  },
  {
    id: 4,
    name: 'PlayStation 5 Slim',
    slug: 'playstation-5-slim',
    brand: 'Sony',
    category: 'Gaming',
    categorySlug: 'gaming',
    images: ['https://via.placeholder.com/300x300/8b5cf6/ffffff?text=PS5'],
    minPrice: 5499,
    maxPrice: 5999,
    offersCount: 5,
    specifications: { 'Stockage': '1 TB', 'Résolution': '4K' },
    createdAt: new Date().toISOString(),
  },
];
