export const mockProducts = [
  {
    id: 1,
    name: 'iPhone 15 Pro 128GB',
    slug: 'iphone-15-pro-128gb',
    brand: 'Apple',
    category: 'Smartphones',
    categorySlug: 'smartphones',
    images: ['https://via.placeholder.com/300x300/0ea5e9/ffffff?text=iPhone+15+Pro'],
    minPrice: 12999,
    maxPrice: 14500,
    offersCount: 3,
    specifications: {
      'Écran': '6.1 pouces',
      'Processeur': 'A17 Pro',
      'RAM': '8 GB',
      'Stockage': '128 GB',
    },
    createdAt: new Date().toISOString(),
  },
  {
    id: 2,
    name: 'Samsung Galaxy S24 Ultra 256GB',
    slug: 'samsung-galaxy-s24-ultra-256gb',
    brand: 'Samsung',
    category: 'Smartphones',
    categorySlug: 'smartphones',
    images: ['https://via.placeholder.com/300x300/6366f1/ffffff?text=Galaxy+S24'],
    minPrice: 15299,
    maxPrice: 16999,
    offersCount: 4,
    specifications: {
      'Écran': '6.8 pouces',
      'Processeur': 'Snapdragon 8 Gen 3',
      'RAM': '12 GB',
      'Stockage': '256 GB',
    },
    createdAt: new Date().toISOString(),
  },
  {
    id: 3,
    name: 'MacBook Air M3 13" 256GB',
    slug: 'macbook-air-m3-13-256gb',
    brand: 'Apple',
    category: 'Ordinateurs',
    categorySlug: 'ordinateurs',
    images: ['https://via.placeholder.com/300x300/10b981/ffffff?text=MacBook+Air+M3'],
    minPrice: 17499,
    maxPrice: 18999,
    offersCount: 2,
    specifications: {
      'Écran': '13.6 pouces',
      'Processeur': 'Apple M3',
      'RAM': '8 GB',
      'Stockage': '256 GB SSD',
    },
    createdAt: new Date().toISOString(),
  },
  {
    id: 4,
    name: 'PlayStation 5 Slim',
    slug: 'playstation-5-slim',
    brand: 'Sony',
    category: 'Gaming',
    categorySlug: 'gaming',
    images: ['https://via.placeholder.com/300x300/8b5cf6/ffffff?text=PS5+Slim'],
    minPrice: 5499,
    maxPrice: 5999,
    offersCount: 5,
    specifications: {
      'Stockage': '1 TB',
      'Lecteur': 'Avec lecteur',
      'Résolution': '4K',
    },
    createdAt: new Date().toISOString(),
  },
  {
    id: 5,
    name: 'AirPods Pro 2ème génération',
    slug: 'airpods-pro-2',
    brand: 'Apple',
    category: 'Audio',
    categorySlug: 'audio',
    images: ['https://via.placeholder.com/300x300/ec4899/ffffff?text=AirPods+Pro'],
    minPrice: 2599,
    maxPrice: 2999,
    offersCount: 3,
    specifications: {
      'Type': 'Sans fil',
      'Réduction de bruit': 'Oui',
      'Autonomie': '6 heures',
    },
    createdAt: new Date().toISOString(),
  },
  {
    id: 6,
    name: 'Dell XPS 15 Intel i7',
    slug: 'dell-xps-15-i7',
    brand: 'Dell',
    category: 'Ordinateurs',
    categorySlug: 'ordinateurs',
    images: ['https://via.placeholder.com/300x300/f59e0b/ffffff?text=Dell+XPS+15'],
    minPrice: 16999,
    maxPrice: 18499,
    offersCount: 2,
    specifications: {
      'Écran': '15.6 pouces',
      'Processeur': 'Intel i7',
      'RAM': '16 GB',
      'Stockage': '512 GB SSD',
    },
    createdAt: new Date().toISOString(),
  },
];
